# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configuration-cache=false
# Fabric Properties
minecraft_version=26.1
loader_version=0.19.3
loom_version=1.15-SNAPSHOT
fabric_kotlin_version=1.13.10+kotlin.2.3.20
kotlin_version=2.3.20
# Mod Properties
mod_version=1.1.2
maven_group=com.chatbridge
archives_base_name=chatbridge
# Dependencies
fabric_api_version=0.145.1+26.1
